apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.4
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      analysis:
        templates:
        - templateName: pass
        - templateName: fail
      steps:
      - setWeight: 10
      - analysis:
          templates:
          - templateName: pass
      - pause: {duration: 30s }
      - setWeight: 100
      - analysis:
          templates:
          - templateName: fail
      - pause: {duration: 30s }
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pass
spec:
  metrics:
  - name: pass
    provider:
      job:
        metadata:
          annotations:
            foo: bar
          labels:
            foo: bar
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: busybox
                command: ["/bin/sh"]
                args: 
                - -c 
                - echo "Pass Rollouts Test" && sleep 30
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fail
spec:
  metrics:
  - name: fail
    provider:
      job:
        metadata:
          annotations:
            foo: bar
          labels:
            foo: bar
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: busybox
                command: ["/bin/sh"]
                args: 
                - -c 
                - echo "Pass Rollouts Test" && sleep 20 && exit 2
              restartPolicy: Never
