apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.5
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      analysis:
        args:
          - name: url
            value: >-
               https://akuity.cloud/api/v1/system/cd/versions
        templates:
        - templateName: pass
        - templateName: fail
      steps:
      - setWeight: 10
      - analysis:
          templates:
          - templateName: pass
      - pause: {duration: 30s }
      - setWeight: 100
      - analysis:
          templates:
          - templateName: fail
      - pause: {duration: 30s }
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pass
spec:
  args:
    - name: url
  metrics:
    - count: 5
      failureLimit: 2
      interval: 15s
      name: http-status-check
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          url: '{{args.url}}'
      successCondition: 'true'
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: faile
spec:
  args:
    - name: url
  metrics:
    - count: 5
      failureLimit: 2
      interval: 15s
      name: http-status-check
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          url: '{{args.url}}'
      successCondition: 'true'
