apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
      - setWeight: 10
      - analysis:
          args:
            - name: url
              value: >-
                http://kube-prometheus-stack-prometheus.monitoring.svc:9090
          templates:
            - templateName: pass
      - pause: {duration: 30s }
      - setWeight: 100
      - pause: {duration: 30s }
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pass
spec:
  args:
    - name: url
  metrics:
    - count: 5
      failureLimit: 2
      interval: 15s
      name: http-status-check
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          url: '{{args.url}}'
      successCondition: 'true'
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fail
spec:
  args:
    - name: url
  metrics:
    - count: 5
      failureLimit: 2
      interval: 15s
      name: http-status-check
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          url: '{{args.url}}'
      successCondition: 'true'
