apiVersion: v1
kind: Service
metadata:
  name: sleep-active
spec:
  selector:
    app: sleep-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sleep-preview
spec:
  selector:
    app: sleep-app
  ports:
    - port: 80
      targetPort: 8080